"""Stage 3: RECONCILIATION. Builds the cross source claims index,
flags candidate duplicates and conflicts mechanically, and validates
the operator's reconciliation decisions."""

from __future__ import annotations

import json
import re
from itertools import combinations
from pathlib import Path

from jinja2 import Environment, FileSystemLoader

from . import config
from .extract import CLAIM_ID_RE, load_all_claims
from .fsutil import iter_jsonl, load_yaml, safe_write
from .gates import require_previous, write_gate

DECISIONS = {"CORROBORATED", "UNIQUE", "SUPERSEDED", "CONFLICT", "OUT_OF_SCOPE"}
GROUP_ID_RE = re.compile(r"^G\d{3}$")
OVERLAP_THRESHOLD = 0.35
TOKEN_RE = re.compile(r"[a-z0-9]+")


def _jinja() -> Environment:
    return Environment(
        loader=FileSystemLoader(str(config.templates_dir())),
        keep_trailing_newline=True,
        trim_blocks=True,
        lstrip_blocks=True,
    )


def _tokens(text: str) -> set[str]:
    return set(TOKEN_RE.findall(text.lower()))


def _candidates(claims: list[dict]) -> list[dict]:
    out = []
    n = 1
    for a, b in combinations(sorted(claims, key=lambda c: c["claim_id"]), 2):
        shared = sorted(set(a["topic_tags"]) & set(b["topic_tags"]))
        if not shared:
            continue
        ta, tb = _tokens(a["claim_text"]), _tokens(b["claim_text"])
        union = ta | tb
        overlap = len(ta & tb) / len(union) if union else 0.0
        if overlap >= OVERLAP_THRESHOLD:
            out.append(
                {
                    "candidate_id": f"P{n:03d}",
                    "claim_ids": [a["claim_id"], b["claim_id"]],
                    "shared_tags": shared,
                    "token_overlap": round(overlap, 3),
                }
            )
            n += 1
    return out


def _locator_hint(claim: dict) -> str:
    """Short deep link hint for the claims index, empty when absent."""
    loc = claim.get("source_locator")
    if not isinstance(loc, dict):
        return ""
    if loc.get("timestamp"):
        return f" @ {loc['timestamp']}"
    if loc.get("page"):
        return f" p. {loc['page']}"
    if loc.get("anchor"):
        return f" #{loc['anchor']}"
    return ""


def _claims_index_md(project: str, claims: list[dict]) -> str:
    by_tag: dict[str, list[dict]] = {}
    for c in claims:
        for tag in c["topic_tags"]:
            by_tag.setdefault(tag, []).append(c)
    lines = [
        f"# Claims index: {project}",
        "",
        "> [!info] Generated by resynth reconcile",
        "> Every extracted claim grouped by topic tag. A claim with several",
        "> tags appears under each of its tags.",
        "",
    ]
    for tag in sorted(by_tag):
        lines.append(f"## {tag}")
        lines.append("")
        for c in sorted(by_tag[tag], key=lambda c: c["claim_id"]):
            lines.append(
                f"- {c['claim_id']} ({c['source_id']}, {c['claim_type']}, "
                f"confidence {c['confidence_as_stated']}){_locator_hint(c)} {c['claim_text']}"
            )
        lines.append("")
    return "\n".join(lines)


def validate_decision(obj: dict, known_claims: set[str], rules: list[str]) -> list[str]:
    errors = []
    required = {"group_id", "claim_ids", "decision", "rule_applied", "decided_by"}
    missing = required - obj.keys()
    errors.extend(f"missing field {f}" for f in sorted(missing))
    if missing:
        return errors
    if not isinstance(obj["group_id"], str) or not GROUP_ID_RE.match(obj["group_id"]):
        errors.append(f"group_id '{obj['group_id']}' does not match GNNN format")
    cids = obj["claim_ids"]
    if not isinstance(cids, list) or not cids:
        errors.append("claim_ids must be a non-empty list")
        cids = []
    for cid in cids:
        if not isinstance(cid, str) or not CLAIM_ID_RE.match(cid):
            errors.append(f"claim id '{cid}' does not match SNN-CNNN format")
        elif cid not in known_claims:
            errors.append(f"claim id '{cid}' was never extracted")
    decision = obj["decision"]
    if decision not in DECISIONS:
        errors.append(f"decision '{decision}' not in {sorted(DECISIONS)}")
    if not isinstance(obj["decided_by"], str) or not obj["decided_by"].strip():
        errors.append("decided_by must be a non-empty string")
    if not isinstance(obj["rule_applied"], str) or not obj["rule_applied"].strip():
        errors.append("rule_applied must be a non-empty string")
    if decision == "SUPERSEDED":
        winner = obj.get("winner")
        if winner not in cids:
            errors.append("SUPERSEDED decision requires a winner drawn from claim_ids")
        if obj["rule_applied"] not in rules:
            errors.append(
                f"SUPERSEDED rule_applied '{obj['rule_applied']}' not in merge-rules.yaml"
            )
    if decision == "OUT_OF_SCOPE" and not str(obj.get("note", "")).strip():
        errors.append("OUT_OF_SCOPE decision requires a one line note giving the reason")
    return errors


def load_decisions(pdir: Path) -> list[dict]:
    path = pdir / "index" / "reconciliation.jsonl"
    if not path.is_file():
        return []
    out = []
    for _lineno, _raw, obj, err in iter_jsonl(path):
        if not err:
            out.append(obj)
    return out


def merge_rules(pdir: Path) -> dict:
    return load_yaml(pdir / "merge-rules.yaml")


def evaluate_gate(pdir: Path, dry_run: bool = False) -> dict:
    claims = load_all_claims(pdir)
    known = {c["claim_id"] for c in claims}
    rules = merge_rules(pdir).get("rules", [])
    reasons: list[str] = []
    path = pdir / "index" / "reconciliation.jsonl"
    decisions = []
    if path.is_file():
        for lineno, _raw, obj, err in iter_jsonl(path):
            if err:
                reasons.append(f"reconciliation.jsonl:{lineno}: {err}")
                continue
            reasons.extend(
                f"reconciliation.jsonl:{lineno}: {e}"
                for e in validate_decision(obj, known, rules)
            )
            decisions.append(obj)
    seen: dict[str, str] = {}
    group_ids: set[str] = set()
    for d in decisions:
        gid = str(d.get("group_id"))
        if gid in group_ids:
            reasons.append(f"duplicate group_id {gid}")
        group_ids.add(gid)
        for cid in d.get("claim_ids") or []:
            if cid in seen:
                reasons.append(f"claim {cid} appears in {seen[cid]} and {gid}")
            else:
                seen[cid] = gid
    undecided = sorted(known - set(seen))
    reasons.extend(f"claim {cid} has no reconciliation decision" for cid in undecided)
    checks = {
        "claims_total": len(known),
        "claims_decided": len(seen),
        "decision_groups": len(decisions),
    }
    return write_gate(pdir, "03-reconcile", reasons, checks, dry_run=dry_run)


def run_reconcile(project: str, dry_run: bool = False) -> dict:
    pdir = config.project_dir(project)
    require_previous(pdir, "03-reconcile")
    claims = load_all_claims(pdir)
    events = []
    index_md = _claims_index_md(project, claims)
    events.append(
        {"file": "claims-index.md", "action": safe_write(pdir / "index" / "claims-index.md", index_md, pdir, dry_run=dry_run)}
    )
    cands = _candidates(claims)
    cand_text = "".join(json.dumps(c) + "\n" for c in cands)
    events.append(
        {"file": "candidates.jsonl", "action": safe_write(pdir / "index" / "candidates.jsonl", cand_text, pdir, dry_run=dry_run)}
    )
    rules = merge_rules(pdir)
    instructions = _jinja().get_template("reconciliation-instructions.md.j2").render(
        project=project, candidates=cands, rules=rules.get("rules", [])
    )
    events.append(
        {
            "file": "RECONCILIATION-INSTRUCTIONS.md",
            "action": safe_write(pdir / "index" / "RECONCILIATION-INSTRUCTIONS.md", instructions, pdir, dry_run=dry_run),
        }
    )
    rec_path = pdir / "index" / "reconciliation.jsonl"
    if not rec_path.exists():
        header = (
            "# RESYNTH reconciliation decisions. One JSON object per line.\n"
            "# Lines starting with # are ignored. See RECONCILIATION-INSTRUCTIONS.md.\n"
            '# Template: {"group_id": "G001", "claim_ids": ["S01-C001"], "decision": "UNIQUE", '
            '"rule_applied": "single_source", "decided_by": "operator", "winner": null, "note": ""}\n'
        )
        events.append(
            {"file": "reconciliation.jsonl", "action": safe_write(rec_path, header, pdir, dry_run=dry_run)}
        )
    gate = evaluate_gate(pdir, dry_run=dry_run)
    return {
        "ok": gate["status"] == "PASS",
        "gate": gate,
        "events": events,
        "candidates": len(cands),
        "messages": [f"{e['file']}: {e['action']}" for e in events]
        + [f"candidate relationships flagged: {len(cands)}", f"gate 03-reconcile: {gate['status']}"]
        + [f"FAIL: {r}" for r in gate["reasons"][:20]],
    }
